# Only specifying non-default values here. For full list and details, see:
# https://prettier.io/docs/en/options.html

bracketSpacing: false
printWidth: 100
semi: false
singleQuote: true
trailingComma: "es5"

